project:
  type: website
  resources:
    - "images/*"
    - "images/LindsayDusard_CV_11.25.pdf"

website:
  title: "Lindsay Dusard"
  search: false
  navbar:
    background: "#246363"
    foreground: white
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: technical assistance.qmd
        text: Other Work
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  
  page-footer: 
    center: "Built with Quarto <br>View source on <a href='https://github.com/ldusard/lindsay-dusard.github.io' >Github</a>"
    border: true
    background: "#246363"
    

format:
  html:
    theme: solar
    css: styles.css
    fontcolor: white
    linkcolor: "#d6eda1"
    toc: false

editor: visual









